batch_size: 32
env_name: WamvNavTwoSetsBuoys-v0
env_type: normal
eps_dec: 0.0001
eps_min: 0.0
epsilon: 1.0
gamma: 0.99
load_checkpoint: false
lr: 0.0005
max_steps: 2000
mem_size: 4000
n_games: 200
replace: 1000
