batch_size: 32
env_name: WamvNavTwoSetsBuoys-v0
env_type: normal
eps_dec: 0.0
eps_min: 0.0
epsilon: 0.0
gamma: 0.99
load_checkpoint: true
lr: 0.0001
max_steps: 1000
mem_size: 5000
n_games: 1
replace: 500
