wamv: #namespace
  task_and_robot_environment_name: 'WamvNavTwoSetsBuoys-v0'
  ros_ws_abspath: "${SIMULATION_DIR}/bachelor_thesis/simulation_ws/"
  environment_type: "normal"
  rospackage_name: "vrx_gazebo"
  launch_file_name: "vrx.launch"
  #dqn params
  gamma: 0.99
  epsilon: 1.0
  n_games: 300
  max_steps: 1000
  algorithm: "dueling-ddqn"
  lr: 0.0001
  mem_size: 10000
  eps_min: 0.00
  batch_size: 32
  replace: 500
  eps_dec: 0.0001
  load_checkpoint: false

buoys:
  n: 17
  red_17:
    x: 18
    y: 62
  red_16:
    x: 23
    y: 65
  red_15:
    x: 28
    y: 68
  red_14:
    x: 33
    y: 71
  red_13:
    x: 38
    y: 74
  red_12:
    x: 43
    y: 77
  red_11:
    x: 48
    y: 80
  red_10:
    x: 53
    y: 83
  red_9:
    x: 58
    y: 86
  red_8:
    x: 63
    y: 87
  red_7:
    x: 68
    y: 88
  red_6:
    x: 73
    y: 87
  red_5:
    x: 78
    y: 86
  red_4:
    x: 83
    y: 83
  red_3:
    x: 88
    y: 80
  red_2:
    x: 93
    y: 77
  red_1:
    x: 98
    y: 74
  green_17:
    x: 18
    y: 34
  green_16:
    x: 23
    y: 37
  green_15:
    x: 28
    y: 40
  green_14:
    x: 33
    y: 43
  green_13:
    x: 38
    y: 46
  green_12:
    x: 43
    y: 49
  green_11:
    x: 48
    y: 52
  green_10:
    x: 53
    y: 55
  green_9:
    x: 58
    y: 58
  green_8:
    x: 63
    y: 69
  green_7:
    x: 68
    y: 70
  green_6:
    x: 73
    y: 69
  green_5:
    x: 78
    y: 68
  green_4:
    x: 83
    y: 65
  green_3:
    x: 88
    y: 62
  green_2:
    x: 93
    y: 59
  green_1:
    x: 98
    y: 56