wamv: #namespace
  task_and_robot_environment_name: 'WamvNavTwoSetsBuoys-v0'
  environment_type: "wide"
  ros_ws_abspath: "/home/angj/priv/bachelor_thesis/simulation_ws/"
  rospackage_name: "vrx_gazebo"
  launch_file_name: "vrx_wide.launch"
  #dqn params
  gamma: 0.99
  epsilon: 1.0
  n_games: 50
  max_steps: 500
  algorithm: "dqn"
  lr: 0.001
  mem_size: 50
  eps_min: 0
  batch_size: 32
  replace: 100
  eps_dec: 0.0001
  load_checkpoint: false

buoys:
  n: 9
  red_9:
    x: 18
    y: 78
  red_8:
    x: 28
    y: 76
  red_7:
    x: 38
    y: 74
  red_6:
    x: 48
    y: 76
  red_5:
    x: 58
    y: 78
  red_4:
    x: 68
    y: 76
  red_3:
    x: 78
    y: 74
  red_2:
    x: 88
    y: 76
  red_1:
    x: 98
    y: 78
  green_9:
    x: 18
    y: 58
  green_8:
    x: 28
    y: 56
  green_7:
    x: 38
    y: 54
  green_6:
    x: 48
    y: 56
  green_5:
    x: 58
    y: 58
  green_4:
    x: 68
    y: 56
  green_3:
    x: 78
    y: 54
  green_2:
    x: 88
    y: 56
  green_1:
    x: 98
    y: 58