wamv: #namespace
    task_and_robot_environment_name: 'WamvNavTwoSetsBuoys-v0'
    ros_ws_abspath: "${SIMULATION_DIR}/bachelor_thesis/simulation_ws/"
    rospackage_name: "vrx_gazebo"
    launch_file_name: "vrx.launch"
    #qlearn parameters
    alpha: 0.1
    gamma: 0.7
    epsilon: 0.9
    epsilon_discount: 0.999
    nepisodes: 500
    nsteps: 10000

results:
    image_path: "${SIMULATION_DIR}/bachelor_thesis/simulation_ws/images/"