// Generated by gencpp from file vrx_gazebo/UsvDrive.msg
// DO NOT EDIT!


#ifndef VRX_GAZEBO_MESSAGE_USVDRIVE_H
#define VRX_GAZEBO_MESSAGE_USVDRIVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vrx_gazebo
{
template <class ContainerAllocator>
struct UsvDrive_
{
  typedef UsvDrive_<ContainerAllocator> Type;

  UsvDrive_()
    : left(0.0)
    , right(0.0)  {
    }
  UsvDrive_(const ContainerAllocator& _alloc)
    : left(0.0)
    , right(0.0)  {
  (void)_alloc;
    }



   typedef float _left_type;
  _left_type left;

   typedef float _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::vrx_gazebo::UsvDrive_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrx_gazebo::UsvDrive_<ContainerAllocator> const> ConstPtr;

}; // struct UsvDrive_

typedef ::vrx_gazebo::UsvDrive_<std::allocator<void> > UsvDrive;

typedef boost::shared_ptr< ::vrx_gazebo::UsvDrive > UsvDrivePtr;
typedef boost::shared_ptr< ::vrx_gazebo::UsvDrive const> UsvDriveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vrx_gazebo::UsvDrive_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vrx_gazebo::UsvDrive_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vrx_gazebo::UsvDrive_<ContainerAllocator1> & lhs, const ::vrx_gazebo::UsvDrive_<ContainerAllocator2> & rhs)
{
  return lhs.left == rhs.left &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vrx_gazebo::UsvDrive_<ContainerAllocator1> & lhs, const ::vrx_gazebo::UsvDrive_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vrx_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vrx_gazebo::UsvDrive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vrx_gazebo::UsvDrive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrx_gazebo::UsvDrive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrx_gazebo::UsvDrive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrx_gazebo::UsvDrive_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrx_gazebo::UsvDrive_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vrx_gazebo::UsvDrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a927990ab5d5c3d628e2d52b8533e52";
  }

  static const char* value(const ::vrx_gazebo::UsvDrive_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a927990ab5d5c3dULL;
  static const uint64_t static_value2 = 0x628e2d52b8533e52ULL;
};

template<class ContainerAllocator>
struct DataType< ::vrx_gazebo::UsvDrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vrx_gazebo/UsvDrive";
  }

  static const char* value(const ::vrx_gazebo::UsvDrive_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vrx_gazebo::UsvDrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Standard USV thrust massage - port and starbard\n"
"\n"
"# Thrust command - typically ranges from {-1.0 - 1.0}\n"
"float32 left\n"
"float32 right\n"
;
  }

  static const char* value(const ::vrx_gazebo::UsvDrive_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vrx_gazebo::UsvDrive_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UsvDrive_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vrx_gazebo::UsvDrive_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vrx_gazebo::UsvDrive_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<float>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<float>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VRX_GAZEBO_MESSAGE_USVDRIVE_H
