wamv: #namespace
    n_actions: 8 # Forwards, Backwards, TurnLeft and TurnRight
    
    propeller_high_speed: 1.0 # High Propeller Speed             
    propeller_low_speed: 0.2 # Low Propeller Speed
    max_angular_speed: 1.0 # Maximum Base Turn Angular speed
   
    work_space: # 3D cube in which Drone is allowed to move
      x_max: 105.0
      x_min: 15.0
      y_max: 88.0
      y_min: 34.0

    desired_point:
      x: 18.0
      y: 53
      z: 1.0
    desired_point_epsilon: 0.5
    max_distance_from_des_point: 105.0 # Maximum distance regitered in observations, has to be bigger than the largest distance of the workspace.
    
    number_decimals_precision_obs: 1

    done_reward: 500.0 # reward
    closer_to_point_reward: 10.0 # reward
    checkpoint_reward: 25.0 # reward